name: Cypress CI Smoke Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run API Tests
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          spec: cypress/e2e/api/login.api.cy.js
        env:
          CYPRESS_BASE_URL: https://test.mycompany.com
          CYPRESS_API_USER: ${{ secrets.API_USER }}
          CYPRESS_API_PASS: ${{ secrets.API_PASS }}


